[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
guide_1 = "2pM5w81J4e2by24CR3fDnZhxxExyq1FsZfkLyw5NcTPJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
